data_root_path: "logs/applications"
file_extension: ".json"
total:
  filename: "total-applications"
  save: true
  send: true
single:
  path: "test-user1"
  filename: "single-application"
  save: true
  send: true
selenium:
  url: "http://localhost:8000"
  driver:
    path: "/usr/bin/chromedriver"
    options:
      - "--disable-gpu"
      - "--no-sandbox"
      - "--disable-dev-shm-usage"
external_url: "http://localhost:8000/approvals/external"
username: "test-user1"
password: "1234"